### PR TITLE
created filter for aurora public art

### PR DESCRIPTION
**Pull request by Sepzie**

### CODE REVIEW

**Review by mbabey — CHANGES_REQUESTED** [review]
File and filter look good.

One change:
* Change the directory name to `united-states/colorado/aurora/public-art-json-to-json.js` to match other US filters

Nice work

**Comment by Sepzie** [comment]
Thank you for the feedback. I made the changes you requested.

**Review by mksample — CHANGES_REQUESTED** [review]
code lgtm but change `aurora/public-art/json-to-json.js` to `aurora/public-art-json-to-json.js`

**Comment by Sepzie** [comment]
@mksample Hi, I made the requested changes. Let me know if it looks good.

**Review by mksample — APPROVED** [review]
lgtm!

**Comment by mksample** [comment]
merging so transmog team can start on some work

**Pull request merged**
