### PR TITLE
Added a filter for USA - NY - New York City

### PR DESCRIPTION
**Pull request by RamilGaripov**

### CODE REVIEW

**Review by mksample — CHANGES_REQUESTED** [review]
Code lgtm, but change the directory name from 'usa' to 'united-states'

**Comment by RamilGaripov** [comment]
> Code lgtm, but change the directory name from 'usa' to 'united-states'

Done! :)

**Review by mksample — CHANGES_REQUESTED** [review]
I missed something, mb. The 'public-art' folder doesn't need to be there and should be removed. The path should be 'filters/united-states/new-york/new-york-city/public-art-json-to-json.js'. Again sorry I missed that.

**Comment by RamilGaripov** [comment]
> I missed something, mb. The 'public-art' folder doesn't need to be there and should be removed. The path should be 'filters/united-states/new-york/new-york-city/public-art-json-to-json.js'. Again sorry I missed that.

Also done!

**Review by mksample — APPROVED** [review]
lgtm!

**Pull request merged**
